name: Bump Version

on:
  workflow_call:

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install -r pip-requirements.txt
          pip install commitizen

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git config --global commit.gpgsign false
          git config --global tag.gpgsign false

      - name: Bump version
        id: bump_version
        run: |
          cz bump --yes
          echo "new_version=$(cz version --project)" >> $GITHUB_OUTPUT

      - name: Push changes
        run: git push --follow-tags

      - name: Output new version
        run: echo ${{ steps.bump_version.outputs.new_version }}
